image: docker:latest

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci

services:
  - docker:dind

stages:
  - build
  - package
  - deploy

maven-test:
  image: maven:3.5.3-jdk-8
  stage: build
  script: "mvn test -B"
  tags:
    - docker
  except:
    - master
    - dev

maven-build:
  image: maven:3.5.3-jdk-8
  stage: build
  script: "mvn package -B"
  tags:
    - docker
  artifacts:
    paths:
      - target/*.jar
    expire_in: 2 weeks
  only:
    - master
    - dev

docker-package:
  stage: package
  script:
  - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  tags:
    - docker
  only:
    - master
    - dev